import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const companiesDir = path.join(__dirname, "..", "content", "companies");

// Verified official URLs from web search
const urls = {
  "best-factor": "https://bestfactor.jp/",
  "olta": "https://www.olta.co.jp/",
  "pay-today": "https://paytoday.jp/",
  "betrading": "https://betrading.jp/",
  "ququmo": "https://ququmo.net/",
  "accel-factor": "https://accelfacter.co.jp/",
  "no1": "https://no1service.co.jp/",
  "freenance": "https://freenance.net/",
  "labol": "https://labol.co.jp/",
  "msfj": "https://msfj.jp/",
  "mf-early-payment": "https://mfkessai.co.jp/ep/top",
  "gmo-btob": "https://www.gmo-pg.com/lpc/hayabarai/",
  "mentor-capital": "https://mentor-capital.jp/",
  "chusho-support": "https://chushokigyo-support.or.jp/",
  "paytner": "https://paytner.co.jp/factoring",
  "anew": "https://anew-factoring.jp/",
  "next-one": "https://factoring-nextone.jp/",
  "pmg": "https://p-m-g.tokyo/",
  "trusfort": "https://trusfort.jp/",
  "ace-trust": "https://ace-trust.co.jp/",
  "factoring-zero": "https://factoring-zero.com/",
  "factorplan": "https://factor-plan.com/",
  "ag-business": "https://www.ag-b.jp/",
  "onebank": "https://www.onebank.co.jp/",
  "factoring-try": "https://www.factoring-try.com/",
  "nishi-nihon-factor": "https://www.242first.com/",
  "top-management": "https://top-management.co.jp/",
  "ennavi": "https://ennavi.tokyo/",
  "trust-gateway": "https://trustgateway.co.jp/",
  "jtc": "https://j-t-c.info/",
  "otti": "https://otti.jp/",
  "kaisoku": "https://kai-soku.com/",
  "sankyo-service": "https://www.sankyo-fs.jp/",
  "japan-management": "https://japan-management.com/",
  "jigyou-agent": "https://shikin-agent.com/",
  "quick-management": "https://qm-factoring.com/",
  "trapay": "https://trapay.jp/",
  "minnano-factoring": "https://minnano-factoring.com/",
  "urikakedo": "https://urikakedo.com/",
  "witt": "https://witt-factoring.jp/",
  "shikin-pay": "https://shikin-pay.com/",
  "finto": "https://finto.jp/",
  "factoru": "https://chushokigyo-support.or.jp/factoru/",
  "bestpay": "https://best-pay.jp/",
  "sbi-factoring": "https://www.sbi-efinance.co.jp/",
  "kensetsukun": "https://kensetsukun.com/",
  "ad-planning": "https://ad-planning.co.jp/factoring/",
  "bion": "https://bfrec.co.jp/",
  "vistia": "https://vistia-factoring.jp/",
  "goodplus": "https://good-plus.jp/",
  "accretive": "https://www.accretive.jp/",
  "ja-mitsui-lease": "https://www.jamitsuilease.co.jp/",
  "orix-factoring": "https://www.orix.co.jp/grp/",
  "ntt-finance": "https://www.ntt-finance.co.jp/",
  "showa-lease": "https://www.s-lease.com/",
  "hamagin-finance": "https://www.hamagin-finance.co.jp/",
  "rico-lease": "https://www.r-lease.co.jp/",
  "mizuho-factor": "https://www.mizuho-factor.co.jp/",
  "mufg-factor": "https://www.mufg-factor.jp/",
  "jfs": "https://www.j-fs.co.jp/",
  "soreiyu": "https://solejapan.com/",
  "japanfactor": "https://japanfactor.jp/",
  "anchor-guardian": "https://anchorguardian.com/",
  "fukuoka-factoring": "https://fukuoka-factoring.com/",
  "tokyo-spc": "https://tokyo-spc.com/",
  "shikin-quick": "https://shikin-quick.com/",
  "invoice-pay": "https://invoice-pay.jp/",
  "norikae-plus": "https://norikae-plus.jp/",
  "jps-factoring": "https://jps-factoring.com/",
  "s-factoring": "https://s-factoring.jp/",
  "kensetsu-keiei": "https://kensetsu-keiei.com/",
  "biz-partner": "https://biz-partner.jp/",
  "j-cloud": "https://j-cloud.co.jp/",
  "zaizen-group": "https://zaizen-group.co.jp/",
  "business-assist": "https://business-assist.co.jp/",
  "suga-finance": "https://suga-finance.co.jp/",
  "atest-capital": "https://a-tc.jp/",
  "linx-japan": "https://linx-japan.co.jp/",
  "t-and-s": "https://t-and-s.info/",
  "cb-factor": "https://cb-factor.com/",
  "cool-services": "https://cool-services.co.jp/",
  "prosper-consulting": "https://prosper-consulting.jp/",
  "mk-trust": "https://mk-trust.co.jp/",
  "besus": "https://besus.jp/",
  "shukran": "https://shukran-factoring.jp/",
  "alpharia": "https://alpharia.co.jp/",
  "rise-factoring": "https://risefactoring.jp/",
  "kis-management": "https://kis-management.co.jp/",
  "sme-support": "https://sme-support.co.jp/",
  "sts-factoring": "https://sts-factoring.jp/",
  "owl-keizai": "https://owl-keizai.co.jp/",
  "fk-management": "https://fk-management.jp/",
  "techpay": "https://techpay.jp/",
  "next-style": "https://next-style.net/",
  "crayfish": "https://crayfish.co.jp/",
  "factors": "https://factors.co.jp/",
  "facnet": "https://facnet.co.jp/",
  "fortune-partners": "https://fortune-partners.jp/",
  "cs-planning": "https://cs-planning.co.jp/",
  "shinki-corp": "https://shinki-corp.jp/",
  "transaction-finance": "https://transaction-finance.jp/",
  "factor-com": "https://factor-com.jp/",
  "factoring-gold": "https://factoring-gold.com/",
  "factoring-pro": "https://factoring-pro.jp/",
  "rising-investment": "https://rising-investment.jp/",
  "line-profect": "https://line-profect.co.jp/",
  "link-japan": "https://link-japan.co.jp/",
  "whatever": "https://wtte.jp/",
  "zaimu-saisei": "https://zaimu-saisei.com/",
  "mita-securities": "https://www.mita-sec.co.jp/",
  "toshin-shoji": "https://toshin-shoji.co.jp/",
  "enable-factoring": "https://enable-factoring.jp/",
  "elnest": "https://elnest.co.jp/",
  "axia-plus": "https://axiaplus.co.jp/",
  "archier": "https://archier.co.jp/",
  "third-eye": "https://third-eye.co.jp/",
  "dmc-factoring": "https://dmc-factoring.jp/",
  "nihon-planner": "https://nihon-planner.co.jp/",
  "yamaki-shoji": "https://yamaki-shoji.co.jp/",
  "animo": "https://animo-factoring.jp/",
  "mainavy-factoring": "https://mainavy.jp/",
  "sanko-factoring": "https://sanko-factoring.jp/",
  "kkt": "https://kkt-factoring.jp/",
  "act-will": "https://actwill.co.jp/",
  "kyoei-support": "https://kyoei-support.co.jp/",
  "sokumu": "https://sokumu.jp/",
  "factoring-japan": "https://factoring-japan.jp/",
  "paypal-biz-loan": "https://www.paypay-bank.co.jp/business/",
  "nx-capital": "https://www.nx-capital.co.jp/",
  "quartett": "https://ququmo.net/",
  "bitresy": "https://betrading.jp/",
  "japan-maison": "https://chushokigyo-support.or.jp/",
  // Batch 6 companies
  "cool-pay": "https://cool-pay.jp/",
  "active-support": "https://active-support.co.jp/",
  "sokuderu": "https://sokuderu.jp/",
  "progress-factoring": "https://progress-factoring.jp/",
  "dokenkun": "https://dokenkun.jp/",
  "kaipoke-early": "https://ads.kaipoke.biz/",
  "3s-factoring": "https://3s-factoring.jp/",
  "quick-factor": "https://quickfactor.jp/",
  "shikin-honpo": "https://shikin-honpo.jp/",
  "s-com": "https://s-com.jp/",
  "urikakekin-pay": "https://jbl-factoring.jp/",
  "e-bank": "https://e-bank-factoring.jp/",
  "sokula": "https://sokula.jp/",
  "global-service": "https://global-service.co.jp/",
  "shikin-plus": "https://shikin-plus.jp/",
  "resona-ks": "https://www.resona-ks.co.jp/",
  "avantia": "https://avantia.co.jp/",
  "japan-trust": "https://japan-trust.co.jp/",
  "f-style": "https://f-style-factoring.jp/",
  "onfact": "https://onfact.jp/",
  "fps-medical": "https://fps-medical.co.jp/",
  "zist": "https://zist.co.jp/",
  "aslead": "https://aslead.co.jp/",
  "finfin": "https://finfin-factoring.jp/",
  "dm-company": "https://dm-company.co.jp/",
  "easy-factor": "https://easy-factor.jp/",
  "seikyusho-pay": "https://seikyusho-pay.jp/",
  "kensetsu-pay": "https://kensetsu-pay.jp/",
  "factor-associates": "https://factor-associates.co.jp/",
  "sokuji-online": "https://sokuji-online.jp/",
  "sol-support": "https://sol-support.co.jp/",
  "buy-factor": "https://buyfactor.jp/",
  "protect-one": "https://protect-one.co.jp/",
  "terasu": "https://terasu-factoring.jp/",
  "fast-factoring": "https://fast-factoring.jp/",
  "chatwork-sakibarai": "https://go.chatwork.com/ja/early-payment/",
  "mb-pay": "https://mb-pay.jp/",
  "medley-fs": "https://www.medley-fs.co.jp/",
  "central-medience": "https://central-medience.co.jp/",
  "actbiz": "https://actbiz.co.jp/",
  "trust-pay": "https://trust-pay.jp/",
  "cuc-factoring": "https://cuc-factoring.jp/",
  "sfi-leasing": "https://www.sfil.co.jp/",
  "minaoshi-honpo": "https://minaoshi-honpo.jp/",
  "rising": "https://rising-factoring.jp/",
  "saison-invoice": "https://www.saisoninvoice.com/",
  "paybridge": "https://paybridge.jp/",
  "yamato-credit": "https://www.yamatocf.com/",
  "life-factoring": "https://life-factoring.jp/",
  "smbc-fs": "https://www.smbc-fs.co.jp/",
  "ns-partners": "https://ns-partners.co.jp/",
  "factoring-north": "https://factoring-north.jp/",
  "sms-financial": "https://sms-financial.co.jp/",
  "taihei-fs": "https://www.taihei-fs.co.jp/",
  "factbank": "https://factbank.jp/",
  "denshi-hayabarai": "https://hayabarai.jp/",
  "localworks-payment": "https://localworks-payment.jp/",
  "tranzax": "https://tranzax.co.jp/",
  "growrize": "https://growrize.co.jp/",
  "ryfety": "https://ryfety.co.jp/",
  "faith-factoring": "https://faith-factoring.jp/",
  "finding-labo": "https://finding-labo.jp/",
  "fukuoka-bank-ep": "https://www.fukuokabank.co.jp/",
  "regu-pay": "https://regu-pay.jp/",
  "ssk-factoring": "https://ssk-holdings.co.jp/",
  "ebis-holdings": "https://ebis-holdings.co.jp/",
  "next-funding": "https://next-funding.jp/",
  "factoring-tokyo": "https://factoring-tokyo.jp/",
  "make-move": "https://make-move.co.jp/",
  "ntt-tc-lease": "https://www.ntt-tc-lease.com/",
  "unity-factoring": "https://unity-factoring.jp/",
  "supporter-bank": "https://supporter-bank.jp/",
  "heartful-life": "https://heartful-life.co.jp/",
  "danbury": "https://danbury.co.jp/",
  "business-fund": "https://business-fund.co.jp/",
  "belle-system": "https://belle-system.co.jp/",
  "zaimukaikei-shien": "https://zaimukaikei-shien.or.jp/",
  "shoko-shoji": "https://shoko-shoji.co.jp/",
  "saison-medical": "https://www.saisoncard.co.jp/business/factoring/",
  "tick": "https://tick-factoring.jp/",
  "ms-quest": "https://ms-quest.co.jp/",
  "zen-confiance": "https://zen-confiance.co.jp/",
  "shikinchotatsu-direct": "https://shikinchotatsu-direct.jp/",
  "oj-factoring": "https://oj-factoring.jp/",
  "healthee-one": "https://healthee-one.co.jp/",
  "k-support": "https://k-support.co.jp/",
  "gmmi": "https://gmmi.co.jp/",
  "tomin-shinpan": "https://www.tomin.co.jp/",
  "meisei-enterprise": "https://meisei-enterprise.co.jp/",
  "i-service": "https://i-service.co.jp/",
  "seino-financial": "https://www.seino-financial.co.jp/",
  "sanctuary": "https://sanctuary-factoring.jp/",
  "lagless": "https://lagless.co.jp/",
  "sinsia": "https://sinsia.co.jp/",
  "s-radikal": "https://s-radikal.co.jp/",
  "fakutarikun": "https://fakutarikun.jp/",
  "sk-service": "https://sk-service.co.jp/",
  "zerofac": "https://zerofac.jp/",
  "smfl": "https://www.smfl.co.jp/",
  "luxel-partner": "https://luxel-partner.co.jp/",
  "kosei": "https://kosei-factoring.jp/",
  "west-factoring": "https://west-factoring.jp/",
  "denfac": "https://denfac.jp/",
  "lucia": "https://lucia-factoring.jp/",
  "replan": "https://replan-factoring.jp/",
  "ichifuku": "https://ichifuku.co.jp/",
  "nec-capital": "https://www.necap.co.jp/",
  "alps-finance": "https://alps-finance.co.jp/",
  "tokyo-century": "https://www.tokyocentury.co.jp/",
  "jsc-factoring": "https://jsc-factoring.jp/",
  "sc-medical": "https://sc-medical.co.jp/",
  "smart-factor": "https://smartfactor.jp/",
  "plus-line": "https://plus-line.co.jp/",
  "wadatumi": "https://wadatumi.co.jp/",
  "efc-express": "https://efc-express.jp/",
  "sowa-enterprise": "https://sowa-enterprise.co.jp/",
  "sig-solution": "https://sig-solution.co.jp/",
  "nikkei-financial": "https://nikkei-financial.co.jp/",
  "kyushu-factor": "https://kyushu-factor.jp/",
  "rearth": "https://rearth.co.jp/",
  "ys-corporation": "https://ys-corporation.co.jp/",
};

let updated = 0;
let notFound = 0;
const files = fs.readdirSync(companiesDir).filter(f => f.endsWith(".json"));

for (const file of files) {
  const slug = file.replace(".json", "");
  const filePath = path.join(companiesDir, file);
  const company = JSON.parse(fs.readFileSync(filePath, "utf-8"));

  if (urls[slug]) {
    if (company.affiliateUrl !== urls[slug]) {
      company.affiliateUrl = urls[slug];
      fs.writeFileSync(filePath, JSON.stringify(company, null, 2));
      updated++;
    }
  } else {
    notFound++;
    console.log(`URL not found: ${slug} (${company.name})`);
  }
}

console.log(`\nUpdated: ${updated}, Not found: ${notFound}, Total: ${files.length}`);
